import { createSlice } from "@reduxjs/toolkit";

// Initial state of the counter
const initialState = { value: 0 }

// Create a slice of the Redux store
const counterSlice = createSlice({
    name: "counter", // Name of the slice, used for debugging and in Redux DevTools
    initialState, // The initial state of this slice
    reducers: {
        increment: (state) => { // Reducer to increment the counter
            state.value += 1; // Directly mutate the state (allowed by Immer)
        },
        decrement: (state) => { // Reducer to decrement the counter
            state.value -= 1; // Directly mutate the state (allowed by Immer)
        }
    }
});

// Export the action creators generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// Export the reducer function to be used in the store
export default counterSlice.reducer; // This is the reducer function that will handle state changes
